version: "3"

networks:
  redis-network:
    driver: bridge

services:
  redis-master:
    image: redis
#    command: redis-server /home/ubuntu/srv/ubuntu/src/main/java/Backend/teampple/infra/redis/redis_6379.conf
    command: redis-server ~/src/main/java/Backend/teampple/infra/redis/redis_6379.conf
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master/data:/data
    networks:
      - redis-network

  redis-slave1:
    image: redis
#    command: redis-server /home/ubuntu/srv/ubuntu/src/main/java/Backend/teampple/infra/redis/redis_6380.conf
    command: redis-server ~/src/main/java/Backend/teampple/infra/redis/redis_6380.conf
    ports:
      - "6380:6380"
#    volumes:
#      - ./redis-slave1/data:/data
    networks:
      - redis-network

  redis-slave2:
    image: redis
#    command: redis-server /home/ubuntu/srv/ubuntu/src/main/java/Backend/teampple/infra/redis/redis_6381.conf
    command: redis-server ~/src/main/java/Backend/teampple/infra/redis/redis_6381.conf
    ports:
      - "6381:6381"
#    volumes:
#      - ./redis-slave2/data:/data
    networks:
      - redis-network

  redis-sentinel1:
    image: redis
#    command: redis-sentinel /home/ubuntu/srv/ubuntu/src/main/java/Backend/teampple/infra/redis/sentinel_26379.conf
    command: redis-sentinel ~/src/main/java/Backend/teampple/infra/redis/sentinel_26379.conf
    ports:
      - "26379:26379"
#    volumes:
#      - ./sentinel1/data:/data
    depends_on:
      - redis-master
    networks:
      - redis-network

  redis-sentinel2:
    image: redis
#    command: redis-sentinel /home/ubuntu/srv/ubuntu/src/main/java/Backend/teampple/infra/redis/sentinel_26380.conf
    command: redis-sentinel ../../../../../Users/jeongsanghun/Desktop/OTHERS/PROJECTS/Teampple_Backend/src/main/java/Backend/teampple/infra/redis/sentinel_26380.conf
    ports:
      - "26380:26380"
#    volumes:
#      - ./sentinel2/data:/data
    depends_on:
      - redis-master
    networks:
      - redis-network

  redis-sentinel3:
    image: redis
#    command: redis-sentinel /home/ubuntu/srv/ubuntu/src/main/java/Backend/teampple/infra/redis/sentinel_26381.conf
    command: redis-sentinel ~/src/main/java/Backend/teampple/infra/redis/sentinel_26381.conf
    ports:
      - "26381:26381"
#    volumes:
#      - ./sentinel3/data:/data
    depends_on:
      - redis-master
    networks:
      - redis-network

#  backend-dev:
#    image: squirmm/teampple-server-dev:dev
#    container_name: backend-dev
#    hostname: backend-dev
#    expose:
#      - "8080"
#
#  nginx:
#    depends_on:
#      - backend-dev
#    restart: always
#    build:
#      dockerfile: Dockerfile
#      context: ./config/nginx
#    ports:
#      - "80:80"