version: "3"

networks:
  redis-network:
    driver: bridge

services:
  redis-master:
    image: redis
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis-master/data:/data
    networks:
      - redis-network

  redis-slave1:
    image: redis
    command: redis-server
    ports:
      - "6380:6380"
    volumes:
      - ./redis-slave1/data:/data
    networks:
      - redis-network

  redis-slave2:
    image: redis
    command: redis-server
    ports:
      - "6381:6381"
    volumes:
      - ./redis-slave2/data:/data
    networks:
      - redis-network

  redis-sentinel1:
    image: redis
    command: redis-sentinel
    ports:
      - "26379:26379"
    volumes:
      - ./sentinel1/data:/data
    depends_on:
      - redis-master
    networks:
      - redis-network

  redis-sentinel2:
    image: redis
    command: redis-sentinel
    ports:
      - "26380:26380"
    volumes:
      - ./sentinel2/data:/data
    depends_on:
      - redis-master
    networks:
      - redis-network

  redis-sentinel3:
    image: redis
    command: redis-sentinel
    ports:
      - "26381:26381"
    volumes:
      - ./sentinel3/data:/data
    depends_on:
      - redis-master
    networks:
      - redis-network

  backend-dev:
    image: squirmm/teampple-server-dev:dev
    container_name: backend-dev
    hostname: backend-dev
    expose:
      - "8080"

  nginx:
    depends_on:
      - backend-dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - "80:80"