version: "3"

services:
  redis:
    image: "redis:alpine"
    network_mode: "host"
    ports:
      - "6379:6379"

  backend-dev:
    image: squirmm/teampple-server-dev:dev
    container_name: backend-dev
    hostname: backend-dev
    network_mode: "host"
    expose:
      - "8080"

  nginx:
    depends_on:
      - backend-dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    network_mode: "host"
    ports:
      - "80:80"