version: "3"

networks:
  redis-network:
    driver: bridge

services:
#  redis:
#    image: bitnami/redis:latest
#    environment:
#      - REDIS_REPLICATION_MODE=master
#      - REDIS_PASSWORD=abcdef
#    networks:
#      - redis-network
#    ports:
#      - 6379:6379
#    container_name: redis-master
#    command: redis-server /home/ubuntu/srv/ubuntu/src/main/java/Backend/teampple/global/config/redis/redis_6379.conf
#  slave-a:
#    container_name: slave-a
#    image: redis:5.0.3
#    ports:
#      - 6380:6379
#    volumes:
#      - ./conf:/usr/local/etc/redis/
#    command: redis-server /home/ubuntu/srv/ubuntu/src/main/java/Backend/teampple/global/config/redis/redis_6380.conf
#  slave-b:
#    container_name: slave-b
#    image: redis
#    ports:
#      - 6381:6379
#    volumes:
#      - ./conf:/usr/local/etc/redis/
#    command: redis-server /home/ubuntu/srv/ubuntu/src/main/java/Backend/teampple/global/config/redis/redis_6381.conf
#
#  sentinel16379:
#    image: redis:5.0.3
#    container_name: sentinel16379
#    hostname: sentinel16379
#    labels:
#      - "name=redis"
#      - "mode=sentinel"
#    network_mode: host
#    ports:
#      - 16379:16379
#    command: redis-sentinel /data/sentinel.conf
#  sentinel16380:
#    image: redis:5.0.3
#    container_name: sentinel16380
#    hostname: sentinel16380
#    labels:
#      - "name=redis"
#      - "mode=sentinel"
#    network_mode: host
#    ports:
#      - 16380:16380
#    command: redis-sentinel /data/sentinel.conf
#  sentinel16381:
#    image: redis:5.0.3
#    container_name: sentinel16381
#    hostname: sentinel16381
#    labels:
#      - "name=redis"
#      - "mode=sentinel"
#    network_mode: host
#    ports:
#      - 16381:16381
#    command: redis-sentinel /data/sentinel.conf
  # master : bitnami/redis:6.2.6
  redis-master:
    hostname: redis-master
    container_name: redis-master
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  # slave1 : bitnami/redis:6.2.6
  redis-slave-1:
    hostname: redis-slave-1
    container_name: redis-slave-1
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6480:6379
    depends_on:
      - redis-master

  # slave2 : bitnami/redis:6.2.6
  redis-slave-2:
    hostname: redis-slave-2
    container_name: redis-slave-2
    image: bitnami/redis:6.2.6
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6481:6379
    depends_on:
      - redis-master
      - redis-slave-1

  # sentinel1 : bitnami/redis-sentinel:6.2.6
  redis-sentinel-1:
    hostname: redis-sentinel-1
    container_name: redis-sentinel-1
    image: bitnami/redis-sentinel:6.2.6
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=master-name
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - 26379:26379

  # sentinel2 : bitnami/redis-sentinel:6.2.6
  redis-sentinel-2:
    hostname: redis-sentinel-2
    container_name: redis-sentinel-2
    image: bitnami/redis-sentinel:6.2.6
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=master-name
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - 26380:26379

  # sentinel3 : bitnami/redis-sentinel:6.2.6
  redis-sentinel-3:
    hostname: redis-sentinel-3
    container_name: redis-sentinel-3
    image: bitnami/redis-sentinel:6.2.6
    environment:
      - REDIS_SENTINEL_DOWN_AFTER_MILLISECONDS=3000
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_SET=master-name
      - REDIS_SENTINEL_QUORUM=2
    depends_on:
      - redis-master
      - redis-slave-1
      - redis-slave-2
    ports:
      - 26381:26379

  backend-dev:
    image: squirmm/teampple-server-dev:dev
    container_name: backend-dev
    hostname: backend-dev
    expose:
      - "8080"

  nginx:
    depends_on:
      - backend-dev
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./config/nginx
    ports:
      - "80:80"
