cloud:
  aws:
    credentials:
      access-key: AKIA256YOGV5R4VQN7XR
      secret-key: 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
    s3:
      bucket: s3-teampple
    region:
      static: ap-northeast-2
    stack:
      auto: false

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://teampple.cwsxloozvnco.ap-northeast-2.rds.amazonaws.com:3306/teampple_test
    username: root
    password: teamppleteam
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
        database-platform: org.hibernate.dialect.MySQL8Dialect
        default_batch_fetch_size: 1000


logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace